import React from "react";
import Navbar from "../components/Navbar";
import { Typography } from "@mui/material";
import '../css/BlogPage.css';

export default function BlogPage() {
    return (
        <>
            <Navbar />
            <div className="blog-area">
            <Typography variant="h3">Blog Title</Typography>
            <Typography variant="h6">by Author Name</Typography>
            <Typography variant="body1">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit sint deserunt, eos quis aperiam est enim eum vero cum a repudiandae numquam quos debitis tenetur expedita consequuntur natus. Unde, officiis dignissimos. Consequatur nulla dolor minus quo id obcaecati dicta recusandae et ducimus. Tempore neque aspernatur dolor in repellendus ratione? Perspiciatis quibusdam quisquam dignissimos odio libero veritatis voluptatum quos deleniti dolorum similique nihil architecto accusantium exercitationem doloribus, voluptates hic. Maxime beatae fugit neque architecto autem facilis molestiae? Officiis, numquam optio perspiciatis error, minus maxime quod eum quos molestiae eligendi similique, deserunt consequatur at nobis in labore autem reiciendis sapiente ad nulla facilis! Facere incidunt qui mollitia officiis ex, beatae, pariatur maiores illo impedit eveniet rerum ea. Optio necessitatibus explicabo harum facilis. Porro ratione eius, ipsam quis ex quam exercitationem necessitatibus. Corporis iure vitae, libero porro dolorum, pariatur voluptates natus quaerat alias vero in enim deleniti quis laborum dolorem? Dignissimos quis ipsum odio similique repellat? Hic voluptate quisquam, nulla odio fugiat, sint in illo consequatur dolor minus libero harum ipsa ex iure unde velit cum mollitia temporibus nesciunt facere voluptates aperiam. Deleniti quae, eum asperiores laborum animi placeat! Animi sapiente, dignissimos suscipit dolor fugiat recusandae culpa ullam quisquam impedit quos dolorum inventore commodi vel quaerat asperiores quis error laudantium possimus, magnam, reiciendis aliquid? Veritatis aspernatur commodi, odio dicta dolore nostrum, suscipit maiores explicabo voluptatibus iste est quod debitis hic officiis ducimus totam cum et sint ipsum! Eaque ullam recusandae repudiandae officia architecto laboriosam maxime, molestias doloribus amet accusamus consequuntur vel ea laborum, minima voluptate excepturi enim vero animi neque. Sequi minus alias laboriosam molestias officiis facilis ea quasi vitae, fuga, aliquam expedita, laudantium repudiandae ab pariatur recusandae tenetur dolore quia rerum culpa neque facere. Molestiae pariatur inventore nesciunt cumque possimus architecto tenetur laborum, aperiam libero blanditiis aspernatur distinctio dolores optio esse!
                Quas quaerat dignissimos molestiae facilis facere, iste deserunt error itaque a doloribus nemo animi, perspiciatis enim odio eos quibusdam nihil consequuntur, quam labore nostrum inventore at? Illo nesciunt consequatur soluta saepe nemo quidem excepturi perspiciatis earum laudantium necessitatibus numquam recusandae voluptatum odit corrupti, blanditiis omnis ipsum similique maxime porro nihil voluptas laborum esse. Aliquid perferendis quasi ipsa ex a, eius explicabo. Alias, vel illo. Dignissimos ullam consectetur voluptatibus aspernatur, amet eum perferendis libero quia quidem? Voluptatem, tempora similique nisi quia alias dolor quos deleniti modi culpa vel. Nesciunt dolores quam sapiente laudantium repellat provident modi enim, rem iste aperiam et minus, distinctio velit nemo voluptate vero ad odio necessitatibus, quas amet excepturi reprehenderit in nam facere. Explicabo voluptates veritatis aut esse possimus obcaecati molestias quas architecto quos perferendis voluptate praesentium, deserunt ipsam officiis, officia atque excepturi dolores nostrum! Porro maxime unde harum esse quia saepe nisi? Ex in porro expedita quo. Quasi iure assumenda, dicta magnam debitis, beatae molestiae reiciendis, iste a deleniti recusandae voluptatibus nobis adipisci consequuntur itaque animi est officiis dignissimos optio facere eaque! Perspiciatis esse, excepturi eius nulla atque autem aliquid reiciendis quae sequi debitis modi expedita reprehenderit dolorem ipsum ipsam quis ex architecto quasi et accusamus repellat!
            </Typography>
            </div>
        </>
    );
}
